path = "C:/Users/bluec/OneDrive/Desktop/ODU/Webpages
url = [path+"/The New York Times - Breaking News, US News, World News and Videos.html",
       path+"/Monkeypox Can Be Airborne, Too - The New York Times.html",
       path+"/Fox News - Breaking News Updates _ Latest News Headlines _ Photos & News Videos.html",
       path+"/30 At-Home Workout Moves_ 20-Minute Set, All Levels, Without Equipment.html",
       path+"/Summer Sale 2022 _ Women's Clothing , Women's Fashion Sale _ SHEIN USA.html",
       path+"/The Best 10 Website Builders.html",
       path+"/Mohamed El-Erian Says Inflation Could Hit 9%, Criticizes Fed.html",
       path+"/Expert Picks_ U.S. Open.html",
       path+"/SciTechDaily - Science, Space and Technology News 2022.html",
       path+"/What went wrong for Astra's failed rocket launch_.html",
       path+"/Ten years after the Higgs, physicists face the nightmare of finding nothing else _ Science _ AAAS.html",
       path+"/June's strawberry supermoon will take the sky Tuesday night - CBS News.html",
       path+"/Plants Appear to Be Breaking Biochemistry Rules by Making 'Secret Decisions'.html",
       path+"/Biofortified tomatoes provide a new route to vitamin D sufficiency _ Nature Plants.html",
       path+"/Ancient trees form bloodlines that bolster forests for thousands of years _ Live Science.html",
       path+"/When cats chew catnip it releases mosquito-repelling chemicals _ New Scientist.html",
       path+"/What Plants Can Do For Your Health _ Healthy Living articles _ Well Being center _ SteadyHealth.com.html",
       path+"/The Inner Life of Cats - Scientific American.html",
       path+"/10 Real-Life Horror Stories - True Horror Stories Reported in the News.html",
       path+"/11 Of The Scariest Ghost Stories From Reddit _ Travel Channel.html",
       path+"/Amanda Aldridge Google Doodle_ celebrating a legendary British composer and opera... - Classic FM.html",
       path+"/LeBron James Stats _ Basketball-Reference.com.html",
       path+"/Amber Heard - IMDb.html",
       path+"/Amber Heard challenges Johnny Depp to his own interview.html",
       path+"/Dark Academia « Post45.html",
       path+"/What is an empath_.html",
       path+"/How The World Butchered Benjamin Franklin’s Quote On Liberty Vs. Security _ TechCrunch.html",
       path+"/Breeze Airways debuts 5 non-stop flights out of Richmond.html",
       path+"/Taco Bell Taco Sauce Recipe - Food.com.html",
       path+"/Guardian_ Sky News Australia is a global hub for climate misinformation – Watts Up With That_.html"]
